/**
 * فقط import نام‌دار Font Awesome — هرگز `import *` از پک solid.
 * UI باید `faIcons` / `<FaIcon>` مصرف کند، نه barrel FA.
 */
import {
  faArrowLeft,
  faArrowRight,
  faBars,
  faBell,
  faBookOpen,
  faBriefcase,
  faBuildingColumns,
  faBullhorn,
  faChalkboardUser,
  faChartColumn,
  faChartLine,
  faChartPie,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleXmark,
  faClipboardCheck,
  faClipboardList,
  faClock,
  faClockRotateLeft,
  faCloudArrowUp,
  faCommentDots,
  faDesktop,
  faDownload,
  faEllipsis,
  faEye,
  faEyeSlash,
  faAward,
  faFile,
  faFileContract,
  faFileInvoice,
  faFilePdf,
  faFolderOpen,
  faImage,
  faGaugeHigh,
  faGraduationCap,
  faHourglassHalf,
  faHouse,
  faIdCard,
  faIdCardClip,
  faKey,
  faLink,
  faLock,
  faMagnifyingGlass,
  faMap,
  faMapLocationDot,
  faMobileScreen,
  faNetworkWired,
  faPenToSquare,
  faListCheck,
  faPaperclip,
  faPaperPlane,
  faPlus,
  faPowerOff,
  faRectangleList,
  faRightFromBracket,
  faRightToBracket,
  faRocket,
  faSchool,
  faScrewdriverWrench,
  faServer,
  faShield,
  faShieldHalved,
  faSliders,
  faSpinner,
  faSun,
  faMoon,
  faTableColumns,
  faTabletScreenButton,
  faTrashCan,
  faTriangleExclamation,
  faUniversity,
  faUnlockKeyhole,
  faUser,
  faUserGear,
  faUserGroup,
  faUserMinus,
  faUserPlus,
  faUserShield,
  faUserTie,
  faWifi,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

export const faIcons = {
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  bars: faBars,
  bell: faBell,
  bookOpen: faBookOpen,
  briefcase: faBriefcase,
  buildingColumns: faBuildingColumns,
  bullhorn: faBullhorn,
  chalkboardUser: faChalkboardUser,
  chartColumn: faChartColumn,
  chartLine: faChartLine,
  chartPie: faChartPie,
  check: faCheck,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronUp: faChevronUp,
  circle: faCircle,
  circleCheck: faCircleCheck,
  circleExclamation: faCircleExclamation,
  circleInfo: faCircleInfo,
  circleXmark: faCircleXmark,
  award: faAward,
  clipboardCheck: faClipboardCheck,
  clipboardList: faClipboardList,
  clock: faClock,
  clockRotateLeft: faClockRotateLeft,
  cloudArrowUp: faCloudArrowUp,
  commentDots: faCommentDots,
  download: faDownload,
  ellipsis: faEllipsis,
  eye: faEye,
  eyeSlash: faEyeSlash,
  file: faFile,
  fileContract: faFileContract,
  fileInvoice: faFileInvoice,
  filePdf: faFilePdf,
  folderOpen: faFolderOpen,
  image: faImage,
  gaugeHigh: faGaugeHigh,
  graduationCap: faGraduationCap,
  hourglassHalf: faHourglassHalf,
  house: faHouse,
  idCard: faIdCard,
  idCardClip: faIdCardClip,
  key: faKey,
  link: faLink,
  lock: faLock,
  magnifyingGlass: faMagnifyingGlass,
  map: faMap,
  mapLocationDot: faMapLocationDot,
  mobileScreen: faMobileScreen,
  networkWired: faNetworkWired,
  penToSquare: faPenToSquare,
  listCheck: faListCheck,
  paperclip: faPaperclip,
  paperPlane: faPaperPlane,
  plus: faPlus,
  powerOff: faPowerOff,
  rectangleList: faRectangleList,
  rightFromBracket: faRightFromBracket,
  rightToBracket: faRightToBracket,
  rocket: faRocket,
  school: faSchool,
  screwdriverWrench: faScrewdriverWrench,
  server: faServer,
  shield: faShield,
  shieldHalved: faShieldHalved,
  sliders: faSliders,
  spinner: faSpinner,
  sun: faSun,
  moon: faMoon,
  tableColumns: faTableColumns,
  tabletScreenButton: faTabletScreenButton,
  desktop: faDesktop,
  trashCan: faTrashCan,
  triangleExclamation: faTriangleExclamation,
  university: faUniversity,
  unlockKeyhole: faUnlockKeyhole,
  user: faUser,
  userGear: faUserGear,
  userGroup: faUserGroup,
  userMinus: faUserMinus,
  userPlus: faUserPlus,
  userShield: faUserShield,
  userTie: faUserTie,
  wifi: faWifi,
  xmark: faXmark,
} as const;